### ISSUE TITLE
Reproducible local testing

### ISSUE THREAD

**Issue by kidmose** [aau-network-security/richkit#114]
We'd like to run test locally in docker, exactly like it runs on Github Actions.

**Comment by mrtrkmn** [comment]
Regarding to running it locally as github actions, I have made some searching on it and I came cross with following tool; 
- [act](https://github.com/nektos/act) - Run your GitHub Actions locally 🚀

However, it is not suitable for Python environment, of course, it is open source project and they are very welcome to make development on that however, I am focusing our issue now :). 

Afterwards, I dig into environments of Github Actions and apparently they are not preferring to use dockers in test cases and they are launching vms. 

https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners

I think, it is not fair to force anyone to launch a vm in their local in order to test richkit's tests, therefore, I am going to write down a command or Dockerfile which will enable a user to test, richkit's tests without effects of their own environment. 

Of course, it approach is also causing other issues like, 

- Tests will not be checked on different OS's since there is no docker image for MacOS, and I am not sure about windows (they are saying that we have however I could not trust that it will work correctly)
- Docker installed environment will be required.

Nevertheless, I think, it is better to have some kind of isolated environment (like everyone else :) ). 

What are your opinions @kidmose and @gianmarcomennecozzi  ?

**Comment by kidmose** [comment]
> ... kind of isolated environment ...

Does this mean you just suggest that we keep using github actions or ... ?

We can invest a lot in making this happen locally, but I'm not sure that it has big enough value to make it worthwhile.

Keeping in mind that I opened this on behalf of you, @mrturkmen06 , I'm happy with concluding that it seems a big effort with questionable returns and therefore closing, but I'm also fine with you exploring it further - your call @mrturkmen06 :)

**Comment by mrtrkmn** [comment]
Yeah, the reason of saying "kind of isolated"  is just using docker, instead of vms, but it has drawbacks as I mentioned above, however, in my opinion, it is the right way to do at the moment, could be changed in time.

**Comment by kidmose** [comment]
Update from checkin meeting: @mrturkmen06 will pursue this

**Comment by mrtrkmn** [comment]
A PoC is implemented however it fails in some cases, I will be checking the reason and pushing the all the changes.

**Comment by mrtrkmn** [comment]
An example implementation has been applied in mentioned branch above.
