### ISSUE TITLE
propose of Makefile 

### ISSUE THREAD

**Issue by mrtrkmn** [aau-network-security/richkit#130]
A `Makefile`  could be useful to  ; 

- create virtualenv for python
- clean  ( cleaning cache files which are  generated  from different cases  )
- linting
- build
-  run test cases  

In my opinion, it could be useful to have it, to have easy interaction with project. What do you think about it @kidmose and @gianmarcomennecozzi  ?

**Comment by kidmose** [comment]
Make files are nice, that's for sure.
But I also find them to be somewhat archaic (Old technology, for old problems).

I think an important principle here is that we don't want to maintain to many things that does solve the same problem - it is wasted effort and your time is our most precious ressource.
So perhaps a good things to consider overall, and for each bullet point is; 
**Is it complimentary (i.e. non-overlapping) to what already exists, or is it so much better a replacement, that it should replace what is already there?** 

So some thoughts;

> create virtualenv for python

Is there one way that fits everyone, and does people need one? (`pyenv` vs. `virtualenv` vs. native vs. `anaconda`)
Can a short text in the README solve this problem (better)?

> clean ( cleaning cache files which are generated from different cases )

Is this pertaining to unittest? Then I think left behind artifacts in the module is a fault and should be fixed in `unittest.TestCase.tearDown[Class]`.
Otherwise and in general: is it worth it to create a `Makefile` to do `git clean -fxd` ?

> linting
build
run test cases

This seems to be covered by Actions and your docker images already, and [tox](https://tox.readthedocs.io/en/latest/) seems to a a more python-oriented solution the good ol' make.

Also, linting - checking and not changing - might fit into a special test case, think a test method for the main module that does something like `import flake8; flake8.run() # I don't know if runs exists`
The autolinting - checking and changing - modifies source files, so that is not a good candidate for a test case, in my opinion.

Overall, I'm not convinced that we need a `Makefile`, but if you are, then I'm fine with it :)

**Comment by mrtrkmn** [comment]
Thanks a lot for the feedback, @kidmose. 

Since creating a `Makefile` does not take too much time, I have just generated and created branch here https://github.com/aau-network-security/richkit/tree/feature/create-makefile-%23130 and `Makefile` is imported with this commit https://github.com/aau-network-security/richkit/commit/c5adc362255314fe27cb7a74047078e44c33abe9

Yeah, in test cases, the generated files  already removed by `tearDown`. 

I do not know, whether it is worthless or worthy to do, however, I have just created. Feel free to do not accept it, I am totally fine with it. ( I can still use it in my local :)  )

**Comment by mrturkmen06** [comment]
btw, test cases are failing due to merge of ct-logs

**Comment by kidmose** [comment]
I meant closes #131 in the merge commit :(

**Comment by mrtrkmn** [comment]
> I meant closes #131 in the merge commit :(

I am not sure, I understand this message @kidmose 


However, seems you have already merged it into develop branch. (Thanks) I am closing the issue , if I missed something or misunderstood something, you can very welcome to open the issue again.

**Comment by kidmose** [comment]
> > I meant closes #131 in the merge commit :(
> 
> I am not sure, I understand this message @kidmose
> 
> However, seems you have already merged it into develop branch. (Thanks) I am closing the issue , if I missed something or misunderstood something, you can very welcome to open the issue again.

I made a typo in the merge commit message. I tried to note the corrections here.
All is good :)
