### ISSUE TITLE
Expected fail ! 

### ISSUE THREAD

**Issue by mrturkmen06** [aau-network-security/richkit#52]
Time to time, google DNS servers (8.8.8.8 8.8.4.4 ) are changing their ASN, which ends up having failure in our tests, ideally, those tests could be skipped.

**Comment by kidmose** [comment]
I'm wondering if there is some way to make use of the reserved, private ASNs to have a more usefull test: https://tools.ietf.org/html/rfc6996#section-5

**Comment by kidmose** [comment]
I'm not sure if we are talking about the same tests, but `richkit/test/test_lookup.py` has two cases, which fails for `master` because the calls to `lookup.country(...)` and `lookup.asn(...)` returns and empty string;

https://github.com/aau-network-security/richkit/runs/425212639#step:6:23

I've created #54 to address this.

**Comment by kidmose** [comment]
This issue might addressed with PRs #71 and #55, and what remains to it might be misunderstandings between @mrturkmen06 and I.

Can you perhaps have a look at those two PRs, and once they are merged, decide if there is more to this issue, @mrturkmen06 ?

**Comment by mrturkmen06** [comment]
After merging mentioned PR's, there is no such an issue, therefore, I am closing the issue.
