### ISSUE TITLE
There are skipped tests

### ISSUE THREAD

**Issue by kidmose** [aau-network-security/richkit#63]
Get an overview of why we have 4 tests that are skipped, create relevant issues, and address them.

```
richkit/test/test_analyse.py ...ss................                       [ 61%]
richkit/test/test_lookup.py ..                                           [ 67%]
richkit/test/test_retrieve.py s...s                                      [ 82%]
richkit/test/test_util.py ......                                         [100%]
```

**Comment by mrturkmen06** [comment]
Current code coverage result: 

<img width="500" alt="Screenshot 2020-03-19 at 14 50 18" src="https://user-images.githubusercontent.com/13614433/77064782-3080be80-69f1-11ea-9ba2-e1a493be08fe.png">

- `retrieve/retrieve/dns.py` has lowest code coverage, reason; has code to test however A and PTR records changes every time. 
- `anaylse.py` has %73 of code coverage, reason; has code to test however it requires to download ALEXA data set, that's why it is skipped in continuous  integration.

**Comment by mrtrkmn** [comment]
The reason of having less code coverage on `analyse.py`  is having skipped tests, most part of `analyse.py` file covered by skipped tests, since tests are skipped, the coverage is lower than expected. The reason of having skipped tests is that it requires alexa database which may take so much time to download and in this case continuous integration might give timeout.
